// Endpoints of the AthleteGuard FastAPI backend (backend/main.py).
export const EP = {
  login: '/auth/login',
  events: '/events',
  manualEvent: '/events/manual',
  assign: (id: number) => `/events/${id}/assign`,
  players: '/players',
  teams: '/teams',
  matches: '/matches',
  clearEvents: '/admin/players/clear',
  users: '/admin/users',
  user: (id: number) => `/admin/users/${id}`,
  system: '/admin/system',
  me: '/auth/me',
  changePassword: '/auth/change-password',
  assessments: '/assessments',
  assessment: (id: number) => `/events/${id}/assessment`,
  resolve: (id: number) => `/events/${id}/resolve`,
  reopen: (id: number) => `/events/${id}/reopen`,
  alertReads: '/alerts/read',
  detector: '/detector/status',
  photos: (playerId: number) => `/players/${playerId}/photos`,
  photo: (playerId: number, name: string) => `/players/${playerId}/photos/${encodeURIComponent(name)}`,
  injuryHistory: '/injury-history',
  playerInjuryHistory: (playerId: number) => `/players/${playerId}/injury-history`,
  injuryRecord: (id: number) => `/injury-history/${id}`,
}